// <auto-generated />
namespace TpModule06.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1ere : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1ere));
        
        string IMigrationMetadata.Id
        {
            get { return "202003241456457_1ere"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
